### ISSUE TITLE
Panic on failed assertion involving 'extend' and 'clear'

### ISSUE THREAD

**Issue by amiraeva** [gnzlbg/slice_deque#47]
Hi - I'm using this library for processing an incoming data stream and I've been running into panics on debug and segfaults in release. I managed to work down the issue into a minimal-ish example:

```
extern crate rand;
extern crate slice_deque;

use rand::{Rng, thread_rng};
use slice_deque::SliceDeque;
use rand::distributions;

const EXTEND_RANGE: usize = 10_000;

fn main() {
    let mut rng = thread_rng();
    let mut sdq = SliceDeque::<u8>::new();

    loop {
        let len = rng.gen_range(1, EXTEND_RANGE);
        
        let rand_bytes = rng.sample_iter::<u8, _>(&distributions::Standard);        
        let rand_bytes = rand_bytes.take(len);
        
        // print out number of bytes written
        println!("{}", len);

        sdq.extend(rand_bytes);
        sdq.clear();
    }
}
```
Here is the error and backtrace I get on my machine (Fedora 28 4.17.14 kernel)
```
thread 'main' panicked at 'assertion failed: x >= -(self.len() as isize) && x <= (self.capacity() - self.len()) as isize', /.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.11/src/lib.rs:806:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:445
   6: <slice_deque::SliceDeque<T>>::move_tail_unchecked
             at ./<panic macros>:3
   7: <slice_deque::SliceDeque<T>>::extend_desugared
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.11/src/lib.rs:1707
   8: <slice_deque::SliceDeque<T> as slice_deque::SpecExtend<T, I>>::spec_extend
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.11/src/lib.rs:2585
   9: <slice_deque::SliceDeque<T> as core::iter::traits::Extend<T>>::extend
             at //.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.11/src/lib.rs:2521
  10: deque_test::main
             at src/main.rs:24
  11: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```
Interestingly, I don't seem to encounter the issue when removing the call to ```clear``` or ```extend``` - it only seems to happen when I use both. Also, both extending with a consistent sized slice (as opposed to a randomly sized iterator) and extending with less than ~10,000 elements prevents the issue from occurring.

Let me know if I'm missing any details that could help!

**Comment by gnzlbg** [comment]
Thanks for the report!

**Comment by gnzlbg** [comment]
So I can reproduce, yay! I'll take it from here :)

**Comment by gnzlbg** [comment]
Minimal working example:

```rust
extern crate slice_deque;
use slice_deque::SliceDeque;
fn main() {
    const N: usize = 4_097;  // 4_096 == page_size is OK
    let mut sdq = SliceDeque::<u8>::new();
    let vec = vec![0_u8; N];
    sdq.extend(vec);
}
```

**Comment by gnzlbg** [comment]
@amiraeva so I've published a new version with a fix that solves this issue. Please do a `cargo update` to use `slice_deque` version `0.1.12` and let me know if you still experience the assert in debug builds or the segfaults in release (luckily, the asserts in debug builds made tracking this one down a breeze).

**Comment by amiraeva** [comment]
The fix seems to have worked, thanks @gnzlbg !

**Comment by gnzlbg** [comment]
Could you try version `0.1.13` as well? It also fixes the performance regression, so now it should be as fast as before and also work properly.

**Comment by amiraeva** [comment]
Can also confirm for ```0.1.13``` - thanks again!

**Comment by gnzlbg** [comment]
Awesome, thank you for the report!
